#
# To run it with a different profile, create the environment variable
# and export it as bellow:
# 
#       export SPRING_PROFILES_ACTIVE=prod
#       export SPRING_PROFILES_ACTIVE=dev
# or:
#       java -jar -Dspring.profiles.active=prod {YOUR-APPLICATION}.jar
#       java -jar -Dspring.profiles.active=dev {YOUR-APPLICATION}.jar
# 
spring:
  config.import: application_dev.yml,application_prod.yml
  profiles.active: dev
