#
# To run it with a different profile, create the environment variable
# and export it as bellow:
# 
#       export SPRING_PROFILES_ACTIVE=prod
#       export SPRING_PROFILES_ACTIVE=dev
# 
const_1: &serverPort ${SPRING_APP_SERVER_PORT:8080}
const_2: &appName ${SPRING_APP_NAME:spring_boot_3_restfull_api}

spring:
  port: *serverPort
  application.name: *appName
  config.activate.on-profile: prod
  # Spring Security credentials
  security:
      user:
         name: admin
         password: password
# LOGGING
logging:
  pattern.console: ${LOGPATTERN_CONSOLE:%cyan(%d{HH:mm:ss.SSS}) %clr(%-5p) %magenta([%thread]) %green(%logger{15}) - %msg%n}
  level:
    web: ${SPRING_WEB_LOG_LEVEL:error}
    com: ${SPRING_LOG_LEVEL:error}
    org:
      springframework:
        # SPRING SECURITY CONFIG
        security: ${SPRING_SECURITY_LOG_LEVEL:error}

corsAllowedOrigins: >
  http://localhost:3000
  http://localhost:${server.port}