ALTER TABLE `members`
    ALTER COLUMN `created_at` timestamp DEFAULT CURRENT_TIMESTAMP();
ALTER TABLE `members`
    ALTER COLUMN `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()